#!/usr/bin/env python3
"""
Build networks/knots-mesh-inplace/ from networks/knots-mesh-pilot/ for
knots_mesh_pilot.py --inplace-switching.

Every node runs the Knots image. A node's camp is set by
<datadir>/switch.conf (pulled in via includeconf): RDTS vbparams present =
Knots camp (v27), absent = Core-compatible camp (v26). The scenario rewrites
switch.conf and restarts bitcoind to switch a node in place.

Per node, relative to knots-mesh-pilot:
  - image -> bitcoin-knots:29.4-local (Core nodes were bitcoindevproject/bitcoin:30.2)
  - config: drop the vbparams line, add includeconf=switch.conf
    (consensusrules=rdts added where missing; it is only the build's consent gate)
  - metadata.initial_camp: v27 for former Knots nodes, v26 for former Core nodes
  - extraInitContainers: seeds switch.conf with the starting camp. bitcoind
    refuses to start if an included file is missing. The file is only written
    if absent, so a pod restart keeps the node's current camp.
Topology (addnode, including the cross-camp bridges) and all other metadata
are unchanged. node-defaults.yaml gets restartPolicy: Always so an RPC stop
restarts bitcoind in the same pod (emptyDir chain data survives).

Needs the warnet chart's extraInitContainers hook
(docs/warnet_changes_required.md, W3).

Also writes scenarios/config/knots_mesh_inplace_network.yaml (the bundled
metadata copy; pass --bundled-network-yaml knots_mesh_inplace_network.yaml).
"""
import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'networks' / 'knots-mesh-pilot'
DST = ROOT / 'networks' / 'knots-mesh-inplace'
BUNDLED = ROOT / 'scenarios' / 'config' / 'knots_mesh_inplace_network.yaml'

KNOTS_IMAGE = {'repository': 'bitcoin-knots', 'tag': '29.4-local'}
RDTS_VBPARAMS = 'vbparams=reduced_data:-1:9223372036854775807'


def seed_container(camp: str) -> dict:
    body = '[regtest]\\n' + (RDTS_VBPARAMS + '\\n' if camp == 'v27' else '')
    return {
        'name': 'seed-switch-conf',
        'image': 'alpine:latest',
        'command': ['/bin/sh', '-c'],
        'args': [f"[ -f /root/.bitcoin/switch.conf ] || printf '{body}' > /root/.bitcoin/switch.conf"],
        'volumeMounts': [{'name': 'data', 'mountPath': '/root/.bitcoin'}],
    }


def convert_node(node: dict) -> dict:
    node = copy.deepcopy(node)
    camp = 'v27' if 'knots' in str(node.get('image', {}).get('repository', '')).lower() else 'v26'
    node['image'] = dict(KNOTS_IMAGE)
    lines = [l for l in node.get('config', '').split('\n')
             if l.strip() and not l.strip().startswith('vbparams=')]
    if not any(l.strip().startswith('consensusrules=') for l in lines):
        lines.append('consensusrules=rdts')
    lines.append('includeconf=switch.conf')
    node['config'] = '\n'.join(lines) + '\n'
    node.setdefault('metadata', {})['initial_camp'] = camp
    node['extraInitContainers'] = [seed_container(camp)]
    return node


def main():
    net = yaml.safe_load((SRC / 'network.yaml').read_text())
    net['nodes'] = [convert_node(n) for n in net['nodes']]
    defaults = yaml.safe_load((SRC / 'node-defaults.yaml').read_text())
    defaults['restartPolicy'] = 'Always'

    DST.mkdir(exist_ok=True)
    header = f"# Generated by tools/make_inplace_network.py from {SRC.name}/ — do not edit by hand.\n"
    (DST / 'network.yaml').write_text(header + yaml.safe_dump(net, sort_keys=False))
    (DST / 'node-defaults.yaml').write_text(header + yaml.safe_dump(defaults, sort_keys=False))
    BUNDLED.write_text(header + yaml.safe_dump(net, sort_keys=False))

    camps = [n['metadata']['initial_camp'] for n in net['nodes']]
    print(f"Wrote {DST.relative_to(ROOT)}/ and {BUNDLED.relative_to(ROOT)}: "
          f"{len(camps)} nodes, v27={camps.count('v27')} v26={camps.count('v26')}")


if __name__ == '__main__':
    main()
