#!/usr/bin/env python3
"""
Convert a network into one for knots_mesh_pilot.py's real-fork modes.

With no arguments: networks/knots-mesh-pilot/ -> networks/knots-mesh-inplace/
plus the bundled copy scenarios/config/knots_mesh_inplace_network.yaml (for
knots_mesh_pilot.py --inplace-switching --bundled-network-yaml
knots_mesh_inplace_network.yaml).

With --src/--dst it converts any network, e.g. one generated by the sweep
pipeline (tools/sweep/2_build_configs.py) from a legacy v26/v27-tagged base,
so the legacy and real-fork methods run from the same scenario spec.

A node's starting camp: Knots image repository or a '27' image tag -> v27
(RDTS), anything else -> v26 (Core).

--style inplace (default): every node runs the Knots image. The camp is set by
  <datadir>/switch.conf (pulled in via includeconf): RDTS vbparams present =
  v27, absent = Core-compatible v26. The scenario rewrites switch.conf and
  restarts bitcoind to switch a node in place. Per node:
    - image -> bitcoin-knots:29.4-local
    - config: drop any vbparams line, add consensusrules=rdts (the build's
      consent gate) and includeconf=switch.conf
    - extraInitContainers: seeds switch.conf with the starting camp. bitcoind
      refuses to start if an included file is missing. Written only if
      absent, so a pod restart keeps the node's current camp.
  node-defaults.yaml gets restartPolicy: Always, so an RPC stop restarts
  bitcoind in the same pod (emptyDir chain data survives). Needs the warnet
  chart's extraInitContainers hook (docs/warnet_changes_required.md, W3).
--style mixed: v27 nodes run Knots with RDTS active from genesis, v26 nodes
  run Core 30.2 (the knots-mesh-pilot layout; switches are accounting only).

Both styles:
  - metadata.initial_camp records the starting camp
  - a legacy per-node `bitcoin_config` dict (not a warnet field, silently
    ignored on deploy) is converted to the real `config` string
  - the topology is kept, but a network made of disconnected islands (every
    legacy base network is two) gets --bridges two-way addnode edges between
    consecutive islands, spread across the node list, as the 5 bridges added
    by hand to knots-mesh-pilot. Without them blocks never cross between
    camps and the split would come from topology, not consensus.
"""
import argparse
import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / 'networks' / 'knots-mesh-pilot'
DEFAULT_DST = ROOT / 'networks' / 'knots-mesh-inplace'
DEFAULT_BUNDLED = ROOT / 'scenarios' / 'config' / 'knots_mesh_inplace_network.yaml'

KNOTS_IMAGE = {'repository': 'bitcoin-knots', 'tag': '29.4-local'}
CORE_IMAGE = {'tag': '30.2'}  # node-defaults repository (bitcoindevproject/bitcoin)
RDTS_VBPARAMS = 'vbparams=reduced_data:-1:9223372036854775807'


def starting_camp(node: dict) -> str:
    image = node.get('image') or {}
    if 'knots' in str(image.get('repository', '')).lower() or '27' in str(image.get('tag', '')):
        return 'v27'
    return 'v26'


def seed_container(camp: str) -> dict:
    body = '[regtest]\\n' + (RDTS_VBPARAMS + '\\n' if camp == 'v27' else '')
    return {
        'name': 'seed-switch-conf',
        'image': 'alpine:latest',
        'command': ['/bin/sh', '-c'],
        'args': [f"[ -f /root/.bitcoin/switch.conf ] || printf '{body}' > /root/.bitcoin/switch.conf"],
        'volumeMounts': [{'name': 'data', 'mountPath': '/root/.bitcoin'}],
    }


def config_lines(node: dict) -> list:
    lines = [l for l in (node.get('config') or '').split('\n') if l.strip()]
    legacy = node.pop('bitcoin_config', None)
    if isinstance(legacy, dict):
        keys = {l.split('=', 1)[0].strip() for l in lines}
        lines += [f"{k}={int(v) if isinstance(v, bool) else v}"
                  for k, v in legacy.items() if k not in keys]
    return [l for l in lines if not l.strip().startswith(('vbparams=', 'consensusrules=', 'includeconf='))]


def convert_node(node: dict, style: str) -> dict:
    node = copy.deepcopy(node)
    camp = starting_camp(node)
    lines = config_lines(node)
    if style == 'inplace':
        node['image'] = dict(KNOTS_IMAGE)
        lines += ['consensusrules=rdts', 'includeconf=switch.conf']
        node['extraInitContainers'] = [seed_container(camp)]
    elif camp == 'v27':
        node['image'] = dict(KNOTS_IMAGE)
        lines += ['consensusrules=rdts', RDTS_VBPARAMS]
    else:
        node['image'] = dict(CORE_IMAGE)
    node['config'] = '\n'.join(lines) + '\n'
    node.setdefault('metadata', {})['initial_camp'] = camp
    return node


def components(nodes: list) -> list:
    names = [n['name'] for n in nodes]
    adj = {n: set() for n in names}
    for n in nodes:
        for peer in n.get('addnode') or []:
            if peer in adj:
                adj[n['name']].add(peer)
                adj[peer].add(n['name'])
    seen, comps = set(), []
    for start in names:
        if start in seen:
            continue
        comp, stack = [], [start]
        while stack:
            x = stack.pop()
            if x in seen:
                continue
            seen.add(x)
            comp.append(x)
            stack.extend(adj[x] - seen)
        comps.append(sorted(comp))
    return comps


def bridge_islands(nodes: list, per_join: int) -> list:
    """Join consecutive islands with per_join two-way addnode edges, picking
    evenly spaced nodes on both sides. Returns the edges added."""
    comps = components(nodes)
    if len(comps) < 2 or per_join <= 0:
        return []
    by_name = {n['name']: n for n in nodes}
    added = []
    for left, right in zip(comps, comps[1:]):
        k = min(per_join, len(left), len(right))
        for i in range(k):
            a = left[int(i * len(left) / k)]
            b = right[int((i * len(right) / k + len(right) / (2 * k))) % len(right)]
            for x, y in ((a, b), (b, a)):
                peers = by_name[x].setdefault('addnode', []) or []
                if y not in peers:
                    peers.append(y)
                by_name[x]['addnode'] = peers
            added.append((a, b))
    return added


def convert_network(net: dict, style: str, bridges: int):
    net = copy.deepcopy(net)
    net['nodes'] = [convert_node(n, style) for n in net['nodes']]
    added = bridge_islands(net['nodes'], bridges)
    return net, added


def convert_defaults(defaults: dict, style: str) -> dict:
    defaults = copy.deepcopy(defaults or {})
    if style == 'inplace':
        defaults['restartPolicy'] = 'Always'
    return defaults


def convert_dir(src: Path, dst: Path, style: str = 'inplace', bridges: int = 5,
                bundled: Path = None) -> dict:
    """Convert src/network.yaml (+ node-defaults.yaml) into dst/. Returns a
    small report dict."""
    net = yaml.safe_load((src / 'network.yaml').read_text())
    defaults_path = src / 'node-defaults.yaml'
    if not defaults_path.exists():
        defaults_path = ROOT / 'networks' / 'node-defaults.yaml'
    defaults = yaml.safe_load(defaults_path.read_text()) if defaults_path.exists() else {}

    out, added = convert_network(net, style, bridges)
    dst.mkdir(parents=True, exist_ok=True)
    try:
        src_label = src.resolve().relative_to(ROOT)
    except ValueError:
        src_label = src
    header = f"# Generated by tools/make_inplace_network.py (--style {style}) from {src_label}/ — do not edit by hand.\n"
    (dst / 'network.yaml').write_text(header + yaml.safe_dump(out, sort_keys=False))
    (dst / 'node-defaults.yaml').write_text(header + yaml.safe_dump(convert_defaults(defaults, style), sort_keys=False))
    if bundled:
        bundled.write_text(header + yaml.safe_dump(out, sort_keys=False))
    camps = [n['metadata']['initial_camp'] for n in out['nodes']]
    return {'nodes': len(camps), 'v27': camps.count('v27'), 'v26': camps.count('v26'),
            'islands_before': len(components(net['nodes'])),
            'islands_after': len(components(out['nodes'])), 'bridges': added}


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--src', type=Path, default=DEFAULT_SRC, help='network directory to convert')
    p.add_argument('--dst', type=Path, default=None, help='output network directory')
    p.add_argument('--style', choices=['inplace', 'mixed'], default='inplace')
    p.add_argument('--bridges', type=int, default=5,
                   help='two-way addnode edges added between consecutive disconnected islands '
                        '(default 5, as in knots-mesh-pilot; 0 = leave the topology alone)')
    p.add_argument('--bundled', type=Path, default=None,
                   help='also write the converted network here (bundled scenario metadata)')
    args = p.parse_args()
    defaults_used = args.src == DEFAULT_SRC and args.dst is None
    dst = args.dst or DEFAULT_DST
    bundled = args.bundled or (DEFAULT_BUNDLED if defaults_used else None)

    report = convert_dir(args.src, dst, args.style, args.bridges, bundled)
    print(f"Wrote {dst}" + (f" and {bundled}" if bundled else "") +
          f": {report['nodes']} nodes, v27={report['v27']} v26={report['v26']}, "
          f"islands {report['islands_before']} -> {report['islands_after']}"
          + (f", bridges {report['bridges']}" if report['bridges'] else ""))


if __name__ == '__main__':
    main()
