#!/usr/bin/env python3
"""
Convert a network into one for knots_mesh_pilot.py's real-fork modes.

With no arguments: networks/knots-mesh-pilot/ -> networks/knots-mesh-inplace/
plus the bundled copy scenarios/config/knots_mesh_inplace_network.yaml (for
knots_mesh_pilot.py --inplace-switching --bundled-network-yaml
knots_mesh_inplace_network.yaml).

With --src/--dst it converts any network, e.g. one generated by the sweep
pipeline (tools/sweep/2_build_configs.py) from a legacy v26/v27-tagged base,
so the legacy and real-fork methods run from the same scenario spec.

A node's starting camp: Knots image repository or a '27' image tag -> v27
(RDTS), anything else -> v26 (Core).

--style inplace (default): every node runs the Knots image. The camp is set by
  <datadir>/switch.conf (pulled in via includeconf): RDTS vbparams present =
  v27, absent = Core-compatible v26. The scenario rewrites switch.conf and
  restarts bitcoind to switch a node in place. Per node:
    - image -> bitcoin-knots:29.4-local
    - config: drop any vbparams line, add consensusrules=rdts (the build's
      consent gate) and includeconf=switch.conf
    - extraInitContainers: seeds switch.conf with the starting camp. bitcoind
      refuses to start if an included file is missing. Written only if
      absent, so a pod restart keeps the node's current camp.
  node-defaults.yaml gets restartPolicy: Always, so an RPC stop restarts
  bitcoind in the same pod (emptyDir chain data survives). Needs the warnet
  chart's extraInitContainers hook (docs/warnet_changes_required.md, W3).
--style mixed: v27 nodes run Knots with RDTS active from genesis, v26 nodes
  run Core 30.2 (the knots-mesh-pilot layout; switches are accounting only).

Both styles:
  - metadata.initial_camp records the starting camp
  - a legacy per-node `bitcoin_config` dict (not a warnet field, silently
    ignored on deploy) is converted to the real `config` string
  - --fork-links N sets how many two-way peer links join nodes that start on
    different forks (default 5, as the 5 bridges added by hand to
    knots-mesh-pilot). The base topology is otherwise kept:
      * too few cross-fork links: add them, preferring links that join
        disconnected islands (every legacy base network is two islands;
        without links blocks never cross between camps), then nodes with the
        fewest cross-fork links, in a --link-seed order;
      * too many (a sweep can put nodes of both forks in one island): remove
        extras, never one whose removal would cut some of a fork's nodes off
        from the rest of that fork (e.g. strand a v26 node inside the v27
        island). So the target can be unreachable; the report says what was
        achieved. Separating the two forks from each other is allowed;
      * islands still left afterwards are joined by same-fork links, which
        don't count toward N (none are possible between single-fork islands,
        e.g. with N=0).
    N=0 with single-fork islands leaves the forks unable to exchange blocks:
    the split then comes from topology, not consensus.
"""
import argparse
import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / 'networks' / 'knots-mesh-pilot'
DEFAULT_DST = ROOT / 'networks' / 'knots-mesh-inplace'
DEFAULT_BUNDLED = ROOT / 'scenarios' / 'config' / 'knots_mesh_inplace_network.yaml'

KNOTS_IMAGE = {'repository': 'bitcoin-knots', 'tag': '29.4-local'}
CORE_IMAGE = {'tag': '30.2'}  # node-defaults repository (bitcoindevproject/bitcoin)
RDTS_VBPARAMS = 'vbparams=reduced_data:-1:9223372036854775807'


def starting_camp(node: dict) -> str:
    image = node.get('image') or {}
    if 'knots' in str(image.get('repository', '')).lower() or '27' in str(image.get('tag', '')):
        return 'v27'
    return 'v26'


def seed_container(camp: str) -> dict:
    body = '[regtest]\\n' + (RDTS_VBPARAMS + '\\n' if camp == 'v27' else '')
    return {
        'name': 'seed-switch-conf',
        'image': 'alpine:latest',
        'command': ['/bin/sh', '-c'],
        'args': [f"[ -f /root/.bitcoin/switch.conf ] || printf '{body}' > /root/.bitcoin/switch.conf"],
        'volumeMounts': [{'name': 'data', 'mountPath': '/root/.bitcoin'}],
    }


def config_lines(node: dict) -> list:
    lines = [l for l in (node.get('config') or '').split('\n') if l.strip()]
    legacy = node.pop('bitcoin_config', None)
    if isinstance(legacy, dict):
        keys = {l.split('=', 1)[0].strip() for l in lines}
        lines += [f"{k}={int(v) if isinstance(v, bool) else v}"
                  for k, v in legacy.items() if k not in keys]
    return [l for l in lines if not l.strip().startswith(('vbparams=', 'consensusrules=', 'includeconf='))]


def convert_node(node: dict, style: str) -> dict:
    node = copy.deepcopy(node)
    camp = starting_camp(node)
    lines = config_lines(node)
    if style == 'inplace':
        node['image'] = dict(KNOTS_IMAGE)
        lines += ['consensusrules=rdts', 'includeconf=switch.conf']
        node['extraInitContainers'] = [seed_container(camp)]
    elif camp == 'v27':
        node['image'] = dict(KNOTS_IMAGE)
        lines += ['consensusrules=rdts', RDTS_VBPARAMS]
    else:
        node['image'] = dict(CORE_IMAGE)
    node['config'] = '\n'.join(lines) + '\n'
    node.setdefault('metadata', {})['initial_camp'] = camp
    return node


def components(nodes: list) -> list:
    names = [n['name'] for n in nodes]
    adj = {n: set() for n in names}
    for n in nodes:
        for peer in n.get('addnode') or []:
            if peer in adj:
                adj[n['name']].add(peer)
                adj[peer].add(n['name'])
    seen, comps = set(), []
    for start in names:
        if start in seen:
            continue
        comp, stack = [], [start]
        while stack:
            x = stack.pop()
            if x in seen:
                continue
            seen.add(x)
            comp.append(x)
            stack.extend(adj[x] - seen)
        comps.append(sorted(comp))
    return comps


def _link(by_name, a, b, on=True):
    """Add (or remove) a two-way addnode link a<->b."""
    for x, y in ((a, b), (b, a)):
        peers = list(by_name[x].get('addnode') or [])
        if on and y not in peers:
            peers.append(y)
        elif not on and y in peers:
            peers.remove(y)
        by_name[x]['addnode'] = peers


def _links(nodes: list) -> set:
    names = {n['name'] for n in nodes}
    return {frozenset((n['name'], p)) for n in nodes for p in (n.get('addnode') or [])
            if p in names and p != n['name']}


def set_fork_links(nodes: list, target, seed: int = 0) -> dict:
    """Make the number of two-way links between nodes on different starting
    forks equal target (see module docstring). Mutates nodes' addnode lists;
    returns a report. target None leaves the topology unchanged."""
    import random
    camp = {n['name']: n['metadata']['initial_camp'] for n in nodes}
    by_name = {n['name']: n for n in nodes}

    def cross_links():
        return sorted((tuple(sorted(e)) for e in _links(nodes) if len({camp[x] for x in e}) == 2))

    before = len(cross_links())
    report = {'fork_links_target': target, 'fork_links_before': before,
              'islands_before': len(components(nodes)), 'added': [], 'removed': [], 'joining_links': []}
    if target is None:
        report.update(fork_links=before, islands_after=report['islands_before'])
        return report

    def fork_fragments():
        # islands each fork's nodes are spread over, summed over forks
        return sum(len({i for i, c in enumerate(components(nodes)) for x in c if camp[x] == f})
                   for f in ('v27', 'v26'))

    rng = random.Random(seed)
    # Too many: drop extras, unless that cuts part of a fork off from the rest of it.
    extras = cross_links()
    rng.shuffle(extras)
    for a, b in extras:
        if len(cross_links()) <= target:
            break
        fragments = fork_fragments()
        _link(by_name, a, b, on=False)
        if fork_fragments() > fragments:
            _link(by_name, a, b, on=True)
        else:
            report['removed'].append((a, b))

    # Too few: add, joining islands first, then the least-linked nodes.
    v27 = [x for x in camp if camp[x] == 'v27']
    v26 = [x for x in camp if camp[x] == 'v26']
    rng.shuffle(v27)
    rng.shuffle(v26)
    rank = {x: i for i, x in enumerate(v27)}
    rank.update({x: i for i, x in enumerate(v26)})
    while len(cross_links()) < target:
        existing = _links(nodes)
        comp_of = {x: i for i, c in enumerate(components(nodes)) for x in c}
        deg = {x: 0 for x in camp}
        for a, b in cross_links():
            deg[a] += 1
            deg[b] += 1
        candidates = [(comp_of[a] == comp_of[b], deg[a] + deg[b], rank[a] + rank[b], a, b)
                      for a in v27 for b in v26 if frozenset((a, b)) not in existing]
        if not candidates:
            break
        *_, a, b = min(candidates)
        _link(by_name, a, b)
        report['added'].append((a, b))

    # Remaining islands: same-fork joining links (not counted toward target).
    while len(components(nodes)) > 1:
        comps = components(nodes)
        comp_of = {x: i for i, c in enumerate(comps) for x in c}
        candidates = [(rank[a] + rank[b], a, b) for a in camp for b in camp
                      if a < b and camp[a] == camp[b] and comp_of[a] != comp_of[b]]
        if not candidates:
            break
        _, a, b = min(candidates)
        _link(by_name, a, b)
        report['joining_links'].append((a, b))

    report.update(fork_links=len(cross_links()), islands_after=len(components(nodes)))
    return report


def convert_network(net: dict, style: str, fork_links=5, link_seed: int = 0):
    net = copy.deepcopy(net)
    net['nodes'] = [convert_node(n, style) for n in net['nodes']]
    report = set_fork_links(net['nodes'], fork_links, link_seed)
    return net, report


def convert_defaults(defaults: dict, style: str) -> dict:
    defaults = copy.deepcopy(defaults or {})
    if style == 'inplace':
        defaults['restartPolicy'] = 'Always'
    return defaults


def convert_dir(src: Path, dst: Path, style: str = 'inplace', fork_links=5,
                bundled: Path = None, link_seed: int = 0) -> dict:
    """Convert src/network.yaml (+ node-defaults.yaml) into dst/. Returns a
    small report dict."""
    net = yaml.safe_load((src / 'network.yaml').read_text())
    defaults_path = src / 'node-defaults.yaml'
    if not defaults_path.exists():
        defaults_path = ROOT / 'networks' / 'node-defaults.yaml'
    defaults = yaml.safe_load(defaults_path.read_text()) if defaults_path.exists() else {}

    out, links = convert_network(net, style, fork_links, link_seed)
    dst.mkdir(parents=True, exist_ok=True)
    try:
        src_label = src.resolve().relative_to(ROOT)
    except ValueError:
        src_label = src
    header = f"# Generated by tools/make_inplace_network.py (--style {style}) from {src_label}/ — do not edit by hand.\n"
    (dst / 'network.yaml').write_text(header + yaml.safe_dump(out, sort_keys=False))
    (dst / 'node-defaults.yaml').write_text(header + yaml.safe_dump(convert_defaults(defaults, style), sort_keys=False))
    if bundled:
        bundled.write_text(header + yaml.safe_dump(out, sort_keys=False))
    camps = [n['metadata']['initial_camp'] for n in out['nodes']]
    return {'nodes': len(camps), 'v27': camps.count('v27'), 'v26': camps.count('v26'), **links}


def describe(report: dict) -> str:
    r = report
    text = (f"{r['nodes']} nodes, v27={r['v27']} v26={r['v26']}, "
            f"fork links {r['fork_links_before']} -> {r['fork_links']}"
            + (f" (target {r['fork_links_target']})" if r['fork_links_target'] is not None else " (unchanged)")
            + f", islands {r['islands_before']} -> {r['islands_after']}")
    if r['fork_links_target'] is not None and r['fork_links'] != r['fork_links_target']:
        text += "  WARNING: target not reachable (removing more would cut nodes off from their own fork)"
    if r['islands_after'] > 1:
        text += ("  NOTE: forks cannot exchange blocks (no links between them)" if r['fork_links'] == 0
                 else "  WARNING: network still has disconnected islands")
    return text


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--src', type=Path, default=DEFAULT_SRC, help='network directory to convert')
    p.add_argument('--dst', type=Path, default=None, help='output network directory')
    p.add_argument('--style', choices=['inplace', 'mixed'], default='inplace')
    p.add_argument('--fork-links', type=int, default=5,
                   help='two-way peer links between nodes starting on different forks '
                        '(default 5, as in knots-mesh-pilot). See the module docstring.')
    p.add_argument('--keep-topology', action='store_true',
                   help='leave addnode links exactly as in --src (ignores --fork-links)')
    p.add_argument('--link-seed', type=int, default=0,
                   help='seed for which links are added/removed (default 0)')
    p.add_argument('--bundled', type=Path, default=None,
                   help='also write the converted network here (bundled scenario metadata)')
    args = p.parse_args()
    defaults_used = args.src == DEFAULT_SRC and args.dst is None
    dst = args.dst or DEFAULT_DST
    bundled = args.bundled or (DEFAULT_BUNDLED if defaults_used else None)

    fork_links = None if args.keep_topology else args.fork_links
    report = convert_dir(args.src, dst, args.style, fork_links, bundled, args.link_seed)
    print(f"Wrote {dst}" + (f" and {bundled}" if bundled else "") + f": {describe(report)}")
    for key in ('added', 'removed', 'joining_links'):
        if report[key]:
            print(f"  {key}: {report[key]}")


if __name__ == '__main__':
    main()
